name: Fetch and Commit JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 12:00 AM
  push:
    branches:
      - 'dist'
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dist
          fetch-depth: 0

      - name: Fetch JSON
        run: |
          curl -o data/SIVR.json https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=SIVR&apikey=${{ secrets.alphaVantage_apikey }}
          git add data/SIVR.json
          curl -o data/SGOL.json https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=SGOL&apikey=${{ secrets.alphaVantage_apikey }}
          git add data/SGOL.json
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git commit -m "Update JSON data [skip ci]"
          git push
