name: Fetch and Commit JSON

on:
  schedule:
    - cron: '23 23 * * MON-FRI'  # At 23:23 on every day-of-week from Monday through Friday
  push:
    branches:
      - 'dist'
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dist
          fetch-depth: 0

      - name: Fetch SIVR JSON
        run: |
          while true; do
            JSON=$(curl -sS https://www.alphavantage.co/query?function=TIME_SERIES_DAILY\&symbol=SIVR\&outputsize=full\&apikey=${{ secrets.ALPHAVANTAGE_APIKEY }})
            if echo "$JSON" | jq -e 'has("Error Message")' >/dev/null; then
              echo "Error message found in JSON. Retrying..."
              sleep 30
            else
              echo "$JSON" > data/SIVR.json
              break
            fi
          done

      - name: Fetch SGOL JSON
        run: |
          while true; do
            JSON=$(curl -sS https://www.alphavantage.co/query?function=TIME_SERIES_DAILY\&symbol=SGOL\&outputsize=full\&apikey=${{ secrets.ALPHAVANTAGE_APIKEY }})
            if echo "$JSON" | jq -e 'has("Error Message")' >/dev/null; then
              echo "Error message found in JSON. Retrying..."
              sleep 30
            else
              echo "$JSON" > data/SGOL.json
              break
            fi
          done

      - name: Commit and Push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data/SIVR.json
          git add data/SGOL.json
          git commit -m "Update JSON data [skip ci]"
          git push
